### ISSUE TITLE
Episode Guide updated incorrectly

### ISSUE THREAD

**Issue by KarellenX** [sualfred/script.metadata.editor#17]
If I set **TV show library is based on information of** to **TVDB**, the nfo file is updated with the `<episodeguide>` URL for TheMovieDB instead.

![metadata](https://user-images.githubusercontent.com/44626605/79061190-f09bb700-7cd0-11ea-8148-94b4aa892703.JPG)

**Comment by KarellenX** [comment]
Also a reminder... could you consider disabling by default the nfo writing :)

**Comment by sualfred** [comment]
@KarellenX 
This is a fallback rule. 
If you set TVDB as default unique ID it should be the TVDB episodeguide.

**Comment by KarellenX** [comment]
Ok. 

Why does the UniqueID need to match the episodeguide? In the current Kodi setup, the two are unrelated. The downside is that if I want to switch scrapers, because maybe the other site has better info for the new episodes, then I can't which was the whole point of being able to modify the episodeguide URL through your add-on.

**Comment by sualfred** [comment]
Counter question: Why should the episodeguide be set in a own setting if you simply can change the uniqueid which represents the used scraper? Isn't it basically the same?

**Comment by KarellenX** [comment]
How can it be the same? The uniqueID is used internally by Kodi. The episodeguide is used by the scrapers to locate the episodes. No scraper uses the uniqueID.

**Comment by sualfred** [comment]
The configured scraper is the default unique ID. If you scrap a movie with the TMDB scraper the TMDB ID is going to be set as the default one.
